SELECT 
	operation_id,
	type,
	(time::TEXT || '+' || translate(operation_time_timezone::TEXT, '+-', '')) as time,
	place,
	sender,
	transaction_time,
	validation_status,
	passenger_id,
	surname,
	name,
	patronymic,
	birthdate,
	passenger_document_id,
	passenger_document_type,
	passenger_document_number,
	passenger_document_disabled_number,
	passenger_document_large_number,
	passenger_type_name,
	passenger_type_type,
	ra_category,
	description,
	is_quota,
	ticket_number,
	ticket_type,
	airline_code,
	depart_place,
	(depart_datetime::TEXT || '+' || translate(depart_datetime_timezone::TEXT, '+-', '')) as depart_datetime,
	arrive_place,
	(arrive_datetime::TEXT || '+' || translate(arrive_datetime_timezone::TEXT, '+-', '')) as arrive_datetime,
	pnr_id,
	operating_airline_code,
	city_from_name,
	airport_from_name,
	city_to_name,
	airport_to_name,
	flight_nums,
	fare_code,
	fare_price
FROM "data_all"
WHERE passenger_document_number = {0} 
ORDER BY time, ticket_number, depart_datetime, type;

