version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  dockerapi:
    image: backend-image:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      ConnectionStrings:TransactionsContext: "Host=postgres_image;Port=5432;Database=ticketsDb;Username=operator;Password=password"
    networks: 
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - ./dbscripts/CreateTables.sql:/docker-entrypoint-initdb.d/CreateTables.sql
    environment:
      POSTGRES_USER: "operator"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "ticketsDb"
    networks:
    - dockerapi-dev
    
volumes:
  dbscripts: